default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: root
  host: localhost
  database: apun_development

test:
  <<: *default
  username: postgres
  password: root
  host: localhost
  database: apun_test

production:
  <<: *default
  database: catedra_apun_production
  username: catedra_apun
  password: <%= ENV["APUN_DATABASE_PASSWORD"] %>
